### ISSUE TITLE
Set up script seems broken

### ISSUE THREAD

**Issue by janet-can** [sodadata/tutorial-demo-project#10]
I was using this repo to update the quick start tutorial in docs and noticed that the script to spin everything up doesn't seem to be working; see below.

Note: the manual setup process works fine, it's the just the script that isn't working.

```
 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/sodadata/tutorial-demo-project/main/scripts/setup.sh)"

This will fetch and unpack the demo in the local directory. Press RETURN to continue or any other key to abort
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6688k  100 6688k    0     0  1257k      0  0:00:05  0:00:05 --:--:-- 1630k
Building soda_sql_project
[+] Building 0.1s (2/2) FINISHED                                                
 => ERROR [internal] load build definition from Dockerfile_soda_sql        0.1s
 => => transferring dockerfile: 53B                                        0.0s
 => CANCELED [internal] load .dockerignore                                 0.0s
 => => transferring context:                                               0.0s
------
 > [internal] load build definition from Dockerfile_soda_sql:
------
failed to solve with frontend dockerfile.v0: failed to read dockerfile: error from sender: open /Users/Janet/.Trash: operation not permitted
ERROR: Service 'soda_sql_project' failed to build : Build failed
Building soda_sql_project
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 968, in run
  File "compose/cli/main.py", line 1426, in run_one_off_container
  File "compose/project.py", line 664, in up
  File "compose/service.py", line 364, in ensure_image_exists
  File "compose/service.py", line 1111, in build
  File "compose/service.py", line 1802, in build
  File "docker/api/build.py", line 159, in build
  File "docker/utils/build.py", line 30, in tar
  File "docker/utils/build.py", line 49, in exclude_paths
  File "docker/utils/build.py", line 215, in rec_walk
  File "docker/utils/build.py", line 215, in rec_walk
  File "docker/utils/build.py", line 215, in rec_walk
  File "docker/utils/build.py", line 185, in rec_walk
PermissionError: [Errno 1] Operation not permitted: '/Users/Janet/Library/Application Support/MobileSync'
[61180] Failed to execute script docker-compose
```

**Comment by janet-can** [comment]
D'oh! I'm such a dummy! The script works. I even wrote the troubleshooting guidance and didn't follow my own instructions. 
Never mind! Sorry @jmarien !
